[default]
tioj_url = "tioj_url"
tioj_username = "username" # leave blank if you don't want to fix it
tioj_password = "password" # leave blank if you don't want to fix it
metadata_schema = "{SCRIPT_DIR}/configs/metadata.schema"
solutions_schema = "{SCRIPT_DIR}/configs/solutions.schema"
subtasks_schema = "{SCRIPT_DIR}/configs/subtasks.schema"
solution_code_verdict = "model_solution"
